export const CHANGE_TAB = "CHANGE_TAB";
export const GET_POSTS = "GET_POSTS";
export const ADD_POST = "ADD_POST";
export const POSTS_LOADING = "POSTS_LOADING";
export const POSTS_LOADED = "POSTS_LOADED";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const TOGGLE_SWITCH = "TOGGLE_SWITCH";
export const FETCH_POST = "FETCH_POST";
export const SAVE_POST = "SAVE_POST";
export const GET_SAVED = "GET_SAVED";
export const SEARCH_POSTS = "SEARCH_POSTS";

// auth / user actions
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
